sudo: false

language: haskell

cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack

env:
  - CABALVER=1.24 GHCVER=8.0.2

script:
  - cabal clean
  - cabal install
  - cabal configure
  - cabal test
