sudo: false

language: haskell

cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack

env:
  - GHCVER=7.6.3
  - GHCVER=7.8.4
  - GHCVER=7.10.3
  - GHCVER=8.0.2
  - GHCVER=8.2.1

script:
  - cabal clean
  - cabal install
  - cabal configure
  - cabal test
